apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ (include "myproject.fullname" .) }}-pods-and-services-info
  labels:
    {{- include "myproject.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: pods-and-services-info
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ (include "myproject.fullname" .) }}-pods-and-services-info
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ (include "myproject.namespace" .) }}