apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ (include "myproject.fullname" .) }}-pods-and-services-info
  labels:
    {{- include "myproject.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: pods-and-services-info
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "list", "watch"]